Update call-build-linux-x86-packages.yml
Signed-off-by: Nikhil Manglore <nmanglor@amazon.com>

diff --git a/.github/workflows/call-build-linux-x86-packages.yml b/.github/workflows/call-build-linux-x86-packages.yml
--- a/.github/workflows/call-build-linux-x86-packages.yml
+++ b/.github/workflows/call-build-linux-x86-packages.yml
@@ -28,9 +28,9 @@ permissions:
   contents: read
 
 jobs:
-  build-and-test-valkey:
+  build-valkey:
     # Capture source tarball and generate checksum for it
-    name: Build and test package ${{ matrix.distro.target }} ${{ matrix.distro.arch }}
+    name: Build package ${{ matrix.distro.target }} ${{ matrix.distro.arch }}
     runs-on: ${{ matrix.distro.target }}
     strategy:
       fail-fast: false
@@ -42,8 +42,14 @@ jobs:
           repository: ${{ github.repository_owner }}/valkey
           ref: ${{ inputs.version }}
 
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ inputs.region }}
+          role-to-assume: ${{ secrets.role_to_assume }}
+
       - name: Install dependencies
-        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libsystemd-dev tcl tcl-tls python3 bc curl
+        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libsystemd-dev
 
       - name: Make Valkey
         run: |
@@ -51,8 +57,6 @@ jobs:
           
           VERSION="${{ inputs.version }}"
           echo "Building for version: $VERSION"
-
-          make -C deps
 
           if [[ "$VERSION" != "unstable" ]]; then
             MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)
@@ -69,7 +73,7 @@ jobs:
           fi
 
       - name: Run Valkey test suite
-        run: timeout 60m make test
+        run: timeout 60m ./runtest
       
       - name: Create Tarball and SHA256sums
         run: |
@@ -82,11 +86,65 @@ jobs:
           mkdir -p packages-files
           cp -rfv $TAR_FILE_NAME.tar* packages-files/
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ inputs.region }}
-          role-to-assume: ${{ secrets.role_to_assume }}
-
       - name: Sync to S3
         run: aws s3 sync packages-files s3://${{ secrets.bucket_name }}/releases/
+
+  test-binaries:
+    name: Test the binaries that were uploaded to S3 - ${{ matrix.distro.platform }}-${{ matrix.distro.arch }}
+    runs-on: ${{ matrix.distro.target }}
+    needs: build-valkey
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJSON(inputs.build_matrix) }}
+    steps:
+      - name: Checkout Valkey
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          repository: ${{ github.repository_owner }}/valkey
+          ref: ${{ inputs.version }}
+          
+      - name: Install all dependencies required for testing
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y \
+          build-essential \
+          tcl \
+          tcl-tls \
+          python3 \
+          libssl-dev \
+          bc \
+          curl
+          
+      - name: Download and validate the binaries from the S3 buckets
+        run: |
+          mkdir -p ./downloaded-x86-binaries
+          cd ./downloaded-x86-binaries
+          
+          TAR_FILE_NAME="valkey-${{ inputs.version }}-${{ matrix.distro.platform }}-${{ matrix.distro.arch }}"
+
+          sleep 30
+          
+          curl -fsSL -o $TAR_FILE_NAME.tar.gz "https://download.valkey.io/releases/$TAR_FILE_NAME.tar.gz"
+          curl -fsSL -o $TAR_FILE_NAME.tar.gz.sha256 "https://download.valkey.io/releases/$TAR_FILE_NAME.tar.gz.sha256"
+          
+          sha256sum -c $TAR_FILE_NAME.tar.gz.sha256
+          tar -xzf $TAR_FILE_NAME.tar.gz
+          
+          if [ ! -x "$TAR_FILE_NAME/bin/valkey-server" ]; then
+              echo "valkey-server not found or not executable"
+              exit 1
+          fi
+          
+          echo "$(pwd)/$TAR_FILE_NAME/bin" >> $GITHUB_PATH
+
+      - name: Run main Valkey test suite
+        run: timeout 60m make test
+
+      - name: Run Valkey Cluster tests
+        run: timeout 20m make test-cluster
+
+      - name: Run Valkey Sentinel tests  
+        run: timeout 20m make test-sentinel
+
+      - name: Run Valkey module tests
+        run: timeout 20m make test-modules
